[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
sycamore = { git = "https://github.com/sycamore-rs/sycamore", rev = "abd556cbc02047042dad2ebd04405e455a9b11b2" }

[build-dependencies]
tonic-build = "0.8"